# Generated by Django 3.2.7 on 2021-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crudst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stemail', models.CharField(max_length=100)),
                ('staddress', models.CharField(max_length=100)),
                ('stmobile', models.IntegerField()),
            ],
        ),
    ]
